version: '3.7'
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - ./video-streaming/src:/usr/src/app/src
    ports:
      - '4000:80'
    restart: 'no'
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    volumes:
      - ./history/src:/usr/src/app/src
    container_name: history
    ports:
      - '4001:80'
    restart: 'no'
